name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Static checks
        run: |
          python -m compileall mcp.py mock_proxy.py
